function Pages() {
}

Pages.items = {
	'/gate': {aaPageName: 'Gate'},
	'/booking/index': {aaPageName: 'Booking^Step1_Search'},
	'/booking/getAvailabilityList': {aaPageName: 'Booking^Step2_Choose flights'},
	'/booking/registerPassenger': {aaPageName: 'Booking^Step3_Passenger'},
	'/booking/extras': {aaPageName: 'Booking^Step4_Extra service'},
	'/booking/payReservation': {aaPageName: 'Booking^Step5_Payment'},
	'/booking/completePayment': {aaPageName: 'Booking^Step6_Booking complete'},
	'/booking/payRefund': {aaPageName: 'Booking^PayRefund'},
	'/login/login': {aaPageName: 'Login^Login'},
	'/member/joinGate': {aaPageName: 'Login^JoinGate'},
	'/member/individual/termsAgree': {aaPageName: 'Login^JoinGate^Individual^TermsAgree'},
	'/member/individual/joinForm': {aaPageName: 'Login^JoinGate^Individual^JoinForm'},
	'/member/individual/joinComplete': {aaPageName: 'Login^JoinGate^Individual^joinComplete'},
	'/member/pwChange': {aaPageName: 'Login^JoinGate^PwChange'},
	'/login/findIdPw': {aaPageName: 'Login^FindIdPw'},
	'/login/findIdPw/resultId': {aaPageName: 'Login^FindIdPw^ResultId'},
	'/login/findIdPw/resultPw': {aaPageName: 'Login^FindIdPw^ResultPw'},
	'/login/findIdPw/noResult': {aaPageName: 'Login^FindIdPw^NoResult'},
	'/mypage/getReservationList': {aaPageName: 'Mypage^ReservationList'},
	'/mypage/getReservationDetail': {aaPageName: 'Mypage^ReservationList^ReservationDetail'},
	'/mypage/nabipoint/pointList': {aaPageName: 'Mypage^MyNabiPoints^PointsList'},
	'/mypage/nabipoint/pointSave': {aaPageName: 'Mypage^MyNabiPoints^EarnPoints'},
	'/mypage/nabipoint/usePoint': {aaPageName: 'Mypage^MyNabiPoints^UsePoints'},
	'/mypage/coupons': {aaPageName: 'Mypage^MyCoupon'},
	'/mypage/qnaList': {aaPageName: 'Mypage^MyQnA'},
	'/mypage/editMemberForm': {aaPageName: 'Mypage^EditMemberForm'},
	'/member/withdrawal': {aaPageName: 'Mypage^EditMemberForm^Withdrawal'},
	'/mypageEmail/email': {aaPageName: 'Mypage^EmailUnsubscribe'},
	'/mypageEmail/emailYn': {aaPageName: 'Mypage^EmailUnsubscribe^Unsubscribed'},
	'/checkin/checkinList': {aaPageName: 'Booking^MyBooking^CheckinList'},
	'/checkin/step1': {aaPageName: 'Booking^MyBooking^CheckinList^Step1_Choose passenger'},
	'/checkin/step2': {aaPageName: 'Booking^MyBooking^CheckinList^Step2_Passenger info'},
	'/checkin/step3': {aaPageName: 'Booking^MyBooking^CheckinList^Step3_Select seat'},
	'/checkin/step4': {aaPageName: 'Booking^MyBooking^CheckinList^Step4_Confirm info'},
	'/checkin/step5': {aaPageName: 'Booking^MyBooking^CheckinList^Step5_Checkin complete'},
	'/checkin/checkinDetail': {aaPageName: 'Booking^MyBooking^CheckinList^CheckinDetail'},
	'/checkin/cancelConfirm': {aaPageName: 'Booking^MyBooking^CheckinList^CancelConfirm'},
	'/checkin/cancelComplete': {aaPageName: 'Booking^MyBooking^CheckinList^CancelComplete'},
	'/ready/flight': {aaPageName: 'Booking^FlightInfo'},
	'/ready/fareRules': {aaPageName: 'Booking^FareRulesInfo'},
	'/ready/discount': {aaPageName: 'Booking^DiscountInfo'},
	'/ready/counter': {aaPageName: 'Service^AirportService^CounterInfo'},
	'/ready/baggage': {aaPageName: 'Service^AirportService^BaggageInfo'},
	'/ready/help': {aaPageName: 'Service^AirportService^HelpInfo'},
	'/ready/checkin': {aaPageName: 'Service^AirportService^CheckinInfo'},
	'/ready/arrivalCard': {aaPageName: 'Service^AirportService^ArrivalCard'},
	'/flight/guide': {aaPageName: 'Service^InflightService^InfligtGuide'},
	'/flight/cabinShopping': {aaPageName: 'Service^InflightService^InfligtShopping'},
	'/flight/taxFree': {aaPageName: 'Service^InflightService^DutyFree'},
	'/flight/jiniInsight': {aaPageName: 'Service^InflightService^InflightMagazine'},
	'/flight/eventflight': {aaPageName: 'Service^InflightService^Eventflight'},
	'/flight/bundle': {aaPageName: 'Service^AncillaryService^BundleService'},
	'/flight/seat': {aaPageName: 'Service^AncillaryService^Seat'},
	'/flight/airlineFood': {aaPageName: 'Service^AncillaryService^InflightMeal'},
	'/flight/jiniPlay': {aaPageName: 'Service^AncillaryService^InflightEntertainment'},
	'/promotion/nowLeave': {aaPageName: 'Benefits^Promotion^Event'},
	'/promotion/eventView': {aaPageName: 'Benefits^Promotion^Event^EventView'},
	'/promotion/endEventView': {aaPageName: 'Benefits^Promotion^Event^EndEventView'},
	'/promotion/winnerView': {aaPageName: 'Benefits^Promotion^Event^WinnerView'},
	'/benefit/jiniCoupon': {aaPageName: 'Benefits^Promotion^JiniCoupon'},
	'/travel/associatedCard': {aaPageName: 'Benefits^CardAndExchange'},
	'/benefit/jinipass': {aaPageName: 'Benefits^BoardingPassDisc'},
	'/travel/jinipass': {aaPageName: 'Benefits^BoardingPassDisc'},
	'/travel/activity': {aaPageName: 'Benefits^Activity'},
	'/travel/hotel': {aaPageName: 'Benefits^Hotel'},
	'/travel/rentcar': {aaPageName: 'Benefits^RentACar'},
	'/travel/insurance': {aaPageName: 'Benefits^Insurance'},
	'/benefit/point': {aaPageName: 'NabiPoints^HowToEarnUsePoints'},
	'/company/announce/announceList': {aaPageName: 'AboutUs^Notice^NoticeList'},
	'/company/announce/announceView': {aaPageName: 'AboutUs^Notice^NoticeList^NoticeView'},
	'/company/career': {aaPageName: 'AboutUs^Employment'},
	'/company/ceo': {aaPageName: 'AboutUs^CEO'},
	'/company/company': {aaPageName: 'AboutUs^CompanyInfo'},
	'/company/governance': {aaPageName: 'AboutUs^Governance'},
	'/company/ethics': {aaPageName: 'AboutUs^Ethics'},
	'/company/ci': {aaPageName: 'AboutUs^CI'},
	'/company/aircraft': {aaPageName: 'AboutUs^Aircraft'},
	'/company/invest/stock': {aaPageName: 'AboutUs^Invest^Stock'},
	'/company/invest/financial': {aaPageName: 'AboutUs^Invest^Financial'},
	'/company/invest/irList': {aaPageName: 'AboutUs^Invest^IRList'},
	'/company/invest/newsList': {aaPageName: 'AboutUs^Invest^NewsList'},
	'/company/freight': {aaPageName: 'AboutUs^Freight'},
	'/company/center/newsList': {aaPageName: 'AboutUs^MediaCenter^NewsList'},
	'/company/center/newsView': {aaPageName: 'AboutUs^MediaCenter^NewsList^NewsView'},
	'/company/center/videoList': {aaPageName: 'AboutUs^MediaCenter^VideoList'},
	'/company/center/adList': {aaPageName: 'AboutUs^MediaCenter^AdList'},
	'/customer/term/privacy/latest': {aaPageName: 'Terms^PrivacyPolicy'},
	'/customer/term/homepageuse/latest': {aaPageName: 'Terms^Terms_Of_Use'},
	'/policy/privacy/latest': {aaPageName: 'Terms^PrivacyPolicy'},
	'/policy/homepageuse/latest': {aaPageName: 'Terms^Terms_Of_Use'},
	'/customer/eTicket': {aaPageName: 'Terms^ITR_Legal_Notice'},
	'/customer/faq': {aaPageName: 'Support^FAQ'},
	'/qna/addQna': {aaPageName: 'Support^QnA_AddQnA'},
	'/promotion/nowMoment': {aaPageName: 'Booking^BookingFlight^LowestTicket'},
	'/promotion/customTicketSearch': {aaPageName: 'Booking^BookingFlight^LowestTicket^CustomTicketSearch'},
	'/promotion/lowestTicketSearch': {aaPageName: 'Booking^BookingFlight^LowestTicket^LowestTicketSearch'}
};

function Page() {
	this.path = location.pathname;

	var indexed = Pages.items[this.path];
	if(!indexed) {
		return {aaPageName: ''};
	}

	this.aaPageName = indexed.aaPageName;
}
